### PR TITLE
Allow optional arguments in pat-leaflet 

### LINKED ISSUE #24: Some tile providers for pat-leaflet cannot be registered
Some tile providers need more than their name to be registered. E.g.
`L.tileLayer.provider('MapBox', {id: 'mapbox.streets', accessToken: 'xxx'}).addTo(map);` 
See https://github.com/leaflet-extras/leaflet-providers#providers-requiring-registration

Currently it is not possible to use such layers with pat-leaflet. Could we change the pattern to allow passing that additional layer-information as configuration?

### PR DESCRIPTION
**Pull request by pbauer**
For tile providers that require registration 
Fixes #24

### CODE REVIEW

**Comment by pbauer** [comment]
@thet done: https://github.com/Patternslib/pat-leaflet/pull/2
What about a Changelog? The repo does not have a changelog or README.

**Comment by pbauer** [comment]
@thet Since I have no rights in the Patternlib-org I cannot add you as a reviewer there. So I ping you here 😃

**Comment by thet** [comment]
Fixed via: https://github.com/Patternslib/pat-leaflet/pull/2

**Comment by thet** [comment]
https://github.com/plone/plone.patternslib/pull/32

**Pull request closed without merging**
